# G23_plot.py
#
# Reads per-step CSVs from a results directory (generated by multi-trial runs)
# Produces:
#   1. G23_plot_bar_<suffix>.png        — Total execution time comparison with error bars
#   2. G23_plot_perstep_<suffix>.png    — Per-step latency (mean ± stddev) for both configs
#   3. G23_results_summary_<suffix>.csv — Aggregated statistics for the report
#
# Usage:
#   python G23_plot.py                  # reads 'results/' → outputs without suffix
#   python G23_plot.py results_0ms      # reads 'results_0ms/' → suffix '_0ms'
#   python G23_plot.py results_25ms     # reads 'results_25ms/' → suffix '_25ms'

import os
import sys
import csv
import glob
import numpy as np
import matplotlib.pyplot as plt
import matplotlib

# ──────────────────────────────────────────────
# Config & CLI parsing
# ──────────────────────────────────────────────
RESULTS_DIR = sys.argv[1] if len(sys.argv) > 1 else "results"

# Derive suffix from folder name: "results_25ms" → "_25ms", "results" → ""
base = os.path.basename(RESULTS_DIR.rstrip("/"))
if base.startswith("results_"):
    SUFFIX = "_" + base[len("results_"):]
elif base == "results":
    SUFFIX = ""
else:
    SUFFIX = "_" + base

matplotlib.rcParams['font.family'] = 'serif'
matplotlib.rcParams['font.serif']  = ['Times New Roman']

COLOR_AFFINITY     = '#4CAF50'
COLOR_ANTIAFFINITY = '#F44336'


# ──────────────────────────────────────────────
# Helper: read one CSV → dict with numpy arrays
# ──────────────────────────────────────────────
def read_trial_csv(filepath):
    """Read a per-step CSV and return step times and cumulative times as arrays."""
    steps, step_times, cumulative = [], [], []
    with open(filepath, "r") as f:
        reader = csv.DictReader(f)
        for row in reader:
            steps.append(int(row["step"]))
            step_times.append(float(row["step_time_sec"]))
            cumulative.append(float(row["cumulative_sec"]))
    return {
        "steps":      np.array(steps),
        "step_times": np.array(step_times),
        "cumulative": np.array(cumulative),
        "total_time": cumulative[-1] if cumulative else 0.0,
    }


# ──────────────────────────────────────────────
# Helper: load all trials for a config
# ──────────────────────────────────────────────
def load_trials(config_name):
    """
    Looks for CSVs matching the config name in RESULTS_DIR.
    Supports both multi-trial (G23_results_affinity_run1.csv, run2, ...)
    and single-run (G23_results_affinity.csv) file patterns.
    """
    pattern = os.path.join(RESULTS_DIR, f"G23_results_{config_name}_run*.csv")
    files = sorted(glob.glob(pattern))

    if not files:
        single = os.path.join(RESULTS_DIR, f"G23_results_{config_name}.csv")
        if os.path.exists(single):
            files = [single]

    if not files:
        print(f"  WARNING: No CSV files found for '{config_name}' in {RESULTS_DIR}/")
        return []

    trials = []
    for f in files:
        try:
            trials.append(read_trial_csv(f))
            print(f"  Loaded: {f} ({trials[-1]['total_time']:.2f}s total)")
        except Exception as e:
            print(f"  ERROR reading {f}: {e}")

    return trials


# ──────────────────────────────────────────────
# Plot 1: Bar chart (total time, with error bars)
# ──────────────────────────────────────────────
def plot_bar_chart(aff_trials, anti_trials):
    aff_totals  = [t["total_time"] for t in aff_trials]
    anti_totals = [t["total_time"] for t in anti_trials]

    aff_mean,  aff_std  = np.mean(aff_totals),  np.std(aff_totals)
    anti_mean, anti_std = np.mean(anti_totals), np.std(anti_totals)

    configs = ['Pod Affinity\n(Same Node)', 'Pod Anti-Affinity\n(Different Nodes)']
    means   = [aff_mean, anti_mean]
    stds    = [aff_std, anti_std]
    colors  = [COLOR_AFFINITY, COLOR_ANTIAFFINITY]

    fig, ax = plt.subplots(figsize=(8, 6))
    bars = ax.bar(configs, means, yerr=stds, capsize=8, color=colors,
                  edgecolor='#333333', linewidth=0.8)

    for bar, mean, std in zip(bars, means, stds):
        label = f"{mean:.2f}s"
        if std > 0:
            label += f" ± {std:.2f}s"
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + std + 0.3,
                label, ha='center', va='bottom', fontweight='bold', fontsize=11)

    if aff_mean > 0:
        slowdown = ((anti_mean - aff_mean) / aff_mean) * 100
        ax.text(0.5, 0.92, f"Slowdown: {slowdown:.1f}%",
                transform=ax.transAxes, ha='center', fontsize=12,
                fontstyle='italic', color='#555555')

    trial_label = f"(n={len(aff_totals)} trials each)" if len(aff_totals) > 1 else "(single run)"
    title_suffix = f" [{SUFFIX.lstrip('_')}]" if SUFFIX else ""
    ax.set_title(f'G23: Distributed ELECTRA Training Execution Time{title_suffix}\n{trial_label}',
                 fontweight='bold', fontsize=13)
    ax.set_ylabel('Execution Time (Seconds)', fontweight='bold')
    ax.grid(axis='y', linestyle='--', alpha=0.7)
    ax.set_axisbelow(True)

    fig.tight_layout()
    outpath = f'G23_plot_bar{SUFFIX}.png'
    fig.savefig(outpath, dpi=300, bbox_inches='tight')
    print(f"\n  ✓ Saved: {outpath}")
    plt.close(fig)


# ──────────────────────────────────────────────
# Plot 2: Per-step line chart (mean ± stddev)
# ──────────────────────────────────────────────
def plot_perstep_chart(aff_trials, anti_trials):
    if not aff_trials or not anti_trials:
        print("  Skipping per-step plot (need data for both configs)")
        return

    num_steps = min(len(aff_trials[0]["step_times"]), len(anti_trials[0]["step_times"]))
    steps     = np.arange(num_steps)

    # Trim all trials to the same length (in case of truncation)
    aff_matrix  = np.array([t["step_times"][:num_steps] for t in aff_trials])
    anti_matrix = np.array([t["step_times"][:num_steps] for t in anti_trials])

    aff_mean,  aff_std  = aff_matrix.mean(axis=0),  aff_matrix.std(axis=0)
    anti_mean, anti_std = anti_matrix.mean(axis=0), anti_matrix.std(axis=0)

    fig, ax = plt.subplots(figsize=(10, 5))

    ax.plot(steps, aff_mean,  color=COLOR_AFFINITY,     linewidth=2, label='Affinity (Same Node)')
    ax.plot(steps, anti_mean, color=COLOR_ANTIAFFINITY,  linewidth=2, label='Anti-Affinity (Different Nodes)')

    if len(aff_trials) > 1:
        ax.fill_between(steps, aff_mean - aff_std,  aff_mean + aff_std,
                         color=COLOR_AFFINITY, alpha=0.15)
        ax.fill_between(steps, anti_mean - anti_std, anti_mean + anti_std,
                         color=COLOR_ANTIAFFINITY, alpha=0.15)

    ax.set_xlabel('Training Step', fontweight='bold')
    ax.set_ylabel('Step Latency (Seconds)', fontweight='bold')

    trial_label = f"mean ± 1σ, n={len(aff_trials)}" if len(aff_trials) > 1 else "single run"
    title_suffix = f" [{SUFFIX.lstrip('_')}]" if SUFFIX else ""
    ax.set_title(f'G23: Per-Step Latency Comparison{title_suffix} ({trial_label})',
                 fontweight='bold', fontsize=13)
    ax.legend(framealpha=0.9)
    ax.grid(True, linestyle='--', alpha=0.5)
    ax.set_axisbelow(True)

    fig.tight_layout()
    outpath = f'G23_plot_perstep{SUFFIX}.png'
    fig.savefig(outpath, dpi=300, bbox_inches='tight')
    print(f"  ✓ Saved: {outpath}")
    plt.close(fig)


# ──────────────────────────────────────────────
# Summary CSV
# ──────────────────────────────────────────────
def write_summary_csv(aff_trials, anti_trials):
    aff_totals  = [t["total_time"] for t in aff_trials]
    anti_totals = [t["total_time"] for t in anti_trials]

    rows = [
        {
            "config":     "affinity",
            "num_trials": len(aff_totals),
            "mean_sec":   round(np.mean(aff_totals), 4),
            "std_sec":    round(np.std(aff_totals), 4),
            "min_sec":    round(np.min(aff_totals), 4),
            "max_sec":    round(np.max(aff_totals), 4),
        },
        {
            "config":     "antiaffinity",
            "num_trials": len(anti_totals),
            "mean_sec":   round(np.mean(anti_totals), 4),
            "std_sec":    round(np.std(anti_totals), 4),
            "min_sec":    round(np.min(anti_totals), 4),
            "max_sec":    round(np.max(anti_totals), 4),
        },
    ]

    outpath = f"G23_results_summary{SUFFIX}.csv"
    with open(outpath, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=rows[0].keys())
        writer.writeheader()
        writer.writerows(rows)

    print(f"  ✓ Saved: {outpath}")


# ──────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────
if __name__ == "__main__":
    print(f"Loading trial data from {RESULTS_DIR}/ (suffix='{SUFFIX}')\n")

    print("Affinity trials:")
    aff_trials = load_trials("affinity")

    print("\nAnti-Affinity trials:")
    anti_trials = load_trials("antiaffinity")

    if not aff_trials and not anti_trials:
        print(f"\nERROR: No data found in {RESULTS_DIR}/")
        print("Run experiments first: make -f G23_Makefile run-all-trials")
        sys.exit(1)

    print("\n── Generating plots ──")
    if aff_trials and anti_trials:
        plot_bar_chart(aff_trials, anti_trials)
        plot_perstep_chart(aff_trials, anti_trials)
        write_summary_csv(aff_trials, anti_trials)
    elif aff_trials:
        print("  Only affinity data found.")
    else:
        print("  Only anti-affinity data found.")

    print("\nDone!")
