# G23_plot.py
#
# Reads per-step CSVs from results/ directory (generated by multi-trial runs)
# Produces:
#   1. G23_plot_bar.png        — Total execution time comparison with error bars
#   2. G23_plot_perstep.png    — Per-step latency (mean ± stddev) for both configs
#   3. G23_results_summary.csv — Aggregated statistics for the report
#
# Also works with single-run CSVs (no error bars in that case).

import os
import csv
import glob
import numpy as np
import matplotlib.pyplot as plt
import matplotlib

# ──────────────────────────────────────────────
# Config
# ──────────────────────────────────────────────
RESULTS_DIR = "results"
matplotlib.rcParams['font.family'] = 'serif'
matplotlib.rcParams['font.serif']  = ['Times New Roman']

COLOR_AFFINITY     = '#4CAF50'
COLOR_ANTIAFFINITY = '#F44336'


# ──────────────────────────────────────────────
# Helper: read one CSV → dict with numpy arrays
# ──────────────────────────────────────────────
def read_trial_csv(filepath):
    """Read a per-step CSV and return step times and cumulative times as arrays."""
    steps, step_times, cumulative = [], [], []
    with open(filepath, "r") as f:
        reader = csv.DictReader(f)
        for row in reader:
            steps.append(int(row["step"]))
            step_times.append(float(row["step_time_sec"]))
            cumulative.append(float(row["cumulative_sec"]))
    return {
        "steps":      np.array(steps),
        "step_times": np.array(step_times),
        "cumulative": np.array(cumulative),
        "total_time": cumulative[-1] if cumulative else 0.0,
    }


# ──────────────────────────────────────────────
# Helper: load all trials for a config
# ──────────────────────────────────────────────
def load_trials(config_name):
    """
    Looks for CSVs matching the config name in RESULTS_DIR.
    Supports both multi-trial (G23_results_affinity_run1.csv, run2, ...)
    and single-run (G23_results_affinity.csv) file patterns.
    """
    # Multi-trial pattern first
    pattern = os.path.join(RESULTS_DIR, f"G23_results_{config_name}_run*.csv")
    files = sorted(glob.glob(pattern))

    # Fallback: single-run file
    if not files:
        single = os.path.join(RESULTS_DIR, f"G23_results_{config_name}.csv")
        if os.path.exists(single):
            files = [single]

    if not files:
        print(f"  WARNING: No CSV files found for '{config_name}' in {RESULTS_DIR}/")
        return []

    trials = []
    for f in files:
        try:
            trials.append(read_trial_csv(f))
            print(f"  Loaded: {f} ({trials[-1]['total_time']:.2f}s total)")
        except Exception as e:
            print(f"  ERROR reading {f}: {e}")

    return trials


# ──────────────────────────────────────────────
# Plot 1: Bar chart (total time, with error bars)
# ──────────────────────────────────────────────
def plot_bar_chart(aff_trials, anti_trials):
    aff_totals  = [t["total_time"] for t in aff_trials]
    anti_totals = [t["total_time"] for t in anti_trials]

    aff_mean,  aff_std  = np.mean(aff_totals),  np.std(aff_totals)
    anti_mean, anti_std = np.mean(anti_totals), np.std(anti_totals)

    configs = ['Pod Affinity\n(Same Node)', 'Pod Anti-Affinity\n(Different Nodes)']
    means   = [aff_mean, anti_mean]
    stds    = [aff_std, anti_std]
    colors  = [COLOR_AFFINITY, COLOR_ANTIAFFINITY]

    fig, ax = plt.subplots(figsize=(8, 6))
    bars = ax.bar(configs, means, yerr=stds, capsize=8, color=colors,
                  edgecolor='#333333', linewidth=0.8)

    # Value labels on top
    for bar, mean, std in zip(bars, means, stds):
        label = f"{mean:.2f}s"
        if std > 0:
            label += f" ± {std:.2f}s"
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + std + 0.3,
                label, ha='center', va='bottom', fontweight='bold', fontsize=11)

    # Slowdown annotation
    if aff_mean > 0:
        slowdown = ((anti_mean - aff_mean) / aff_mean) * 100
        ax.text(0.5, 0.92, f"Slowdown: {slowdown:.1f}%",
                transform=ax.transAxes, ha='center', fontsize=12,
                fontstyle='italic', color='#555555')

    trial_label = f"(n={len(aff_totals)} trials each)" if len(aff_totals) > 1 else "(single run)"
    ax.set_title(f'G23: Distributed ELECTRA Training Execution Time\n{trial_label}',
                 fontweight='bold', fontsize=13)
    ax.set_ylabel('Execution Time (Seconds)', fontweight='bold')
    ax.grid(axis='y', linestyle='--', alpha=0.7)
    ax.set_axisbelow(True)

    fig.tight_layout()
    fig.savefig('G23_plot_bar.png', dpi=300, bbox_inches='tight')
    print("\n  ✓ Saved: G23_plot_bar.png")
    plt.close(fig)


# ──────────────────────────────────────────────
# Plot 2: Per-step line chart (mean ± stddev)
# ──────────────────────────────────────────────
def plot_perstep_chart(aff_trials, anti_trials):
    if not aff_trials or not anti_trials:
        print("  Skipping per-step plot (need data for both configs)")
        return

    num_steps = len(aff_trials[0]["step_times"])
    steps     = np.arange(num_steps)

    # Stack all trials into 2D arrays: (num_trials, num_steps)
    aff_matrix  = np.array([t["step_times"] for t in aff_trials])
    anti_matrix = np.array([t["step_times"] for t in anti_trials])

    aff_mean,  aff_std  = aff_matrix.mean(axis=0),  aff_matrix.std(axis=0)
    anti_mean, anti_std = anti_matrix.mean(axis=0), anti_matrix.std(axis=0)

    fig, ax = plt.subplots(figsize=(10, 5))

    # Mean lines
    ax.plot(steps, aff_mean,  color=COLOR_AFFINITY,     linewidth=2, label='Affinity (Same Node)')
    ax.plot(steps, anti_mean, color=COLOR_ANTIAFFINITY,  linewidth=2, label='Anti-Affinity (Different Nodes)')

    # Confidence bands (± 1 std dev) — only if multi-trial
    if len(aff_trials) > 1:
        ax.fill_between(steps, aff_mean - aff_std,  aff_mean + aff_std,
                         color=COLOR_AFFINITY, alpha=0.15)
        ax.fill_between(steps, anti_mean - anti_std, anti_mean + anti_std,
                         color=COLOR_ANTIAFFINITY, alpha=0.15)

    ax.set_xlabel('Training Step', fontweight='bold')
    ax.set_ylabel('Step Latency (Seconds)', fontweight='bold')

    trial_label = f"mean ± 1σ, n={len(aff_trials)}" if len(aff_trials) > 1 else "single run"
    ax.set_title(f'G23: Per-Step Latency Comparison ({trial_label})', fontweight='bold', fontsize=13)
    ax.legend(framealpha=0.9)
    ax.grid(True, linestyle='--', alpha=0.5)
    ax.set_axisbelow(True)

    fig.tight_layout()
    fig.savefig('G23_plot_perstep.png', dpi=300, bbox_inches='tight')
    print("  ✓ Saved: G23_plot_perstep.png")
    plt.close(fig)


# ──────────────────────────────────────────────
# Summary CSV: aggregated stats for the report
# ──────────────────────────────────────────────
def write_summary_csv(aff_trials, anti_trials):
    aff_totals  = [t["total_time"] for t in aff_trials]
    anti_totals = [t["total_time"] for t in anti_trials]

    rows = [
        {
            "config":     "affinity",
            "num_trials": len(aff_totals),
            "mean_sec":   round(np.mean(aff_totals), 4),
            "std_sec":    round(np.std(aff_totals), 4),
            "min_sec":    round(np.min(aff_totals), 4),
            "max_sec":    round(np.max(aff_totals), 4),
        },
        {
            "config":     "antiaffinity",
            "num_trials": len(anti_totals),
            "mean_sec":   round(np.mean(anti_totals), 4),
            "std_sec":    round(np.std(anti_totals), 4),
            "min_sec":    round(np.min(anti_totals), 4),
            "max_sec":    round(np.max(anti_totals), 4),
        },
    ]

    outpath = "G23_results_summary.csv"
    with open(outpath, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=rows[0].keys())
        writer.writeheader()
        writer.writerows(rows)

    print(f"  ✓ Saved: {outpath}")


# ──────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────
if __name__ == "__main__":
    print(f"Loading trial data from {RESULTS_DIR}/...\n")

    print("Affinity trials:")
    aff_trials = load_trials("affinity")

    print("\nAnti-Affinity trials:")
    anti_trials = load_trials("antiaffinity")

    if not aff_trials and not anti_trials:
        print("\nERROR: No data found. Run experiments first:")
        print("  make -f G23_Makefile run-all-trials")
        exit(1)

    print("\n── Generating plots ──")
    if aff_trials and anti_trials:
        plot_bar_chart(aff_trials, anti_trials)
        plot_perstep_chart(aff_trials, anti_trials)
        write_summary_csv(aff_trials, anti_trials)
    elif aff_trials:
        print("  Only affinity data found. Run anti-affinity experiments too.")
    else:
        print("  Only anti-affinity data found. Run affinity experiments too.")

    print("\nDone!")